import Foundation

public enum ShellKind: String, CaseIterable, Sendable {
    case fish
    case sh
    case bash
    case zsh
}

public struct ShellEmitter: Sendable {
    public init() {}

    public func emit(kind: ShellKind, storedPaths: [String]) -> String {
        switch kind {
        case .fish:
            emitFish(storedPaths: storedPaths)
        case .sh, .bash, .zsh:
            emitSh(storedPaths: storedPaths)
        }
    }

    public func loaderSnippet(kind: ShellKind, binaryName: String = "unipath") -> String {
        switch kind {
        case .fish:
            """
            # >>> unipath initialize >>>
            if command -q \(binaryName)
                \(binaryName) env fish | source
            end
            # <<< unipath initialize <<<
            """
        case .sh, .bash, .zsh:
            """
            # >>> unipath initialize >>>
            if command -v \(binaryName) >/dev/null 2>&1; then
              eval "$(\(binaryName) env sh)"
            fi
            # <<< unipath initialize <<<
            """
        }
    }

    private func emitFish(storedPaths: [String]) -> String {
        let quoted = storedPaths.map(fishQuote).joined(separator: " ")
        return """
        # Generated by unipath. Evaluate with: unipath env fish | source
        set -l __unipath_managed
        for __unipath_path in \(quoted)
            set -l __unipath_expanded (string replace -r '^~(?=/|$)' -- $HOME "$__unipath_path")
            set __unipath_expanded (string replace -r '^\\$HOME(?=/|$)' -- $HOME "$__unipath_expanded")
            set __unipath_expanded (string replace -r '^\\$\\{HOME\\}(?=/|$)' -- $HOME "$__unipath_expanded")
            if test -d "$__unipath_expanded"; and not contains -- "$__unipath_expanded" $__unipath_managed
                set -a __unipath_managed "$__unipath_expanded"
            end
        end
        for __unipath_path in $PATH
            if not contains -- "$__unipath_path" $__unipath_managed
                set -a __unipath_managed "$__unipath_path"
            end
        end
        set -gx PATH $__unipath_managed
        set -e __unipath_managed __unipath_path __unipath_expanded
        """
    }

    private func emitSh(storedPaths: [String]) -> String {
        let body = storedPaths.joined(separator: "\n")
        return """
        # Generated by unipath. Evaluate with: eval "$(unipath env sh)"
        __unipath_managed=
        while IFS= read -r __unipath_path; do
          case "$__unipath_path" in
            "~") __unipath_expanded="$HOME" ;;
            "~/"*) __unipath_expanded="$HOME/${__unipath_path#~/}" ;;
            "\\$HOME") __unipath_expanded="$HOME" ;;
            "\\$HOME/"*) __unipath_expanded="$HOME/${__unipath_path#\\$HOME/}" ;;
            "\\${HOME}") __unipath_expanded="$HOME" ;;
            "\\${HOME}/"*) __unipath_expanded="$HOME/${__unipath_path#\\${HOME}/}" ;;
            *) __unipath_expanded="$__unipath_path" ;;
          esac
          [ -d "$__unipath_expanded" ] || continue
          case ":$__unipath_managed:" in
            *":$__unipath_expanded:"*) ;;
            *) __unipath_managed="${__unipath_managed:+$__unipath_managed:}$__unipath_expanded" ;;
          esac
        done <<'__UNIPATH_PATHS__'
        \(body)
        __UNIPATH_PATHS__

        __unipath_existing=$PATH
        PATH=$__unipath_managed
        __unipath_old_ifs=$IFS
        IFS=:
        for __unipath_path in $__unipath_existing; do
          [ -n "$__unipath_path" ] || continue
          case ":$PATH:" in
            *":$__unipath_path:"*) ;;
            *) PATH="${PATH:+$PATH:}$__unipath_path" ;;
          esac
        done
        IFS=$__unipath_old_ifs
        export PATH
        unset __unipath_managed __unipath_path __unipath_expanded __unipath_existing __unipath_old_ifs
        """
    }

    private func fishQuote(_ value: String) -> String {
        let escaped = value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "$", with: "\\$")
        return "\"\(escaped)\""
    }
}

